import { FormEvent, useCallback, useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { toast } from "react-toastify";
import { useAuth } from "../../../helper/useAuth";
import useCSRF from "../../../helper/useCSRF";
import { requestAdminStepUp } from "../../../helper/adminStepUp";
import { PageHeader } from "../ui";

type Report = { subscriptionRevenueMGA: number; marketplacePaymentsMGA: number; grossRevenueMGA: number; refundsMGA: number; netRevenueMGA: number; paymentCount: number; forecastNext30DaysMGA: number; byDay: { date: string; amountMGA: number }[]; reconciliationNote: string };
type StaffRole = "Support" | "Moderator" | "Finance" | "Read Only";
const money = (amount: number) => `${Number(amount || 0).toLocaleString("fr-FR")} MGA`;
const rolePermissions: Record<StaffRole, string[]> = { Support: ["support.read", "support.reply", "support.manage"], Moderator: ["moderation.review"], Finance: ["finance.read", "finance.refund", "finance.payout"], "Read Only": ["support.read", "finance.read"] };

export default function FinancialDashboard() {
  const { user } = useAuth();
  const csrf = useCSRF();
  const isSuperAdmin = user?.userGroupMember_id?.usergroup_id?.name === "Super Admin";
  const canReadFinance = isSuperAdmin || user?.adminPermissions?.includes("finance.read") === true;
  const canRefund = isSuperAdmin || user?.adminPermissions?.includes("finance.refund") === true;
  const canPayout = isSuperAdmin || user?.adminPermissions?.includes("finance.payout") === true;
  const now = new Date();
  const [from, setFrom] = useState(new Date(now.getTime() - 30 * 86400000).toISOString().slice(0, 10));
  const [to, setTo] = useState(now.toISOString().slice(0, 10));
  const [report, setReport] = useState<Report | null>(null);
  const [rates, setRates] = useState({ EUR: "", USD: "", updatedAt: "" });
  const [refundForm, setRefundForm] = useState({ sourceType: "subscription", sourceId: "", amount: "", note: "" });
  const [payouts, setPayouts] = useState<any[]>([]);
  const [payoutDraft, setPayoutDraft] = useState<Record<string, { amount: string; reference: string }>>({});
  const [staff, setStaff] = useState<any[]>([]);
  const [staffDraft, setStaffDraft] = useState<Record<string, { role: StaffRole; permissions: string[] }>>({});
  const [newStaffId, setNewStaffId] = useState("");
  const [newStaffRole, setNewStaffRole] = useState<StaffRole>("Support");
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);

  const loadReport = useCallback(async () => {
    setLoading(true);
    try { const response = await fetch(`${import.meta.env.REACT_API_URL}admin/finance?from=${from}&to=${to}T23:59:59.999`, { credentials: "include" }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setReport(result.data); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Rapport indisponible."); }
    finally { setLoading(false); }
  }, [from, to]);
  const loadRates = useCallback(async () => { const response = await fetch(`${import.meta.env.REACT_API_URL}admin/currency-rates`, { credentials: "include" }); if (response.ok) { const result = await response.json(); setRates({ EUR: result.data?.EUR ? String(result.data.EUR) : "", USD: result.data?.USD ? String(result.data.USD) : "", updatedAt: result.data?.updatedAt ?? "" }); } }, []);
  const loadPayouts = useCallback(async () => { const response = await fetch(`${import.meta.env.REACT_API_URL}admin/finance/seller-payouts`, { credentials: "include" }); if (response.ok) setPayouts((await response.json()).data ?? []); }, []);
  const loadStaff = useCallback(async () => { const response = await fetch(`${import.meta.env.REACT_API_URL}admin/staff`, { credentials: "include" }); if (response.ok) setStaff((await response.json()).data ?? []); }, []);
  useEffect(() => {
    if (!canReadFinance) return;
    void loadReport();
    void loadPayouts();
    if (isSuperAdmin) { void loadRates(); void loadStaff(); }
  }, [canReadFinance, isSuperAdmin, loadReport, loadRates, loadPayouts, loadStaff]);

  const saveRates = async (event: FormEvent) => { if (!isSuperAdmin) return; event.preventDefault(); if (!csrf) return; setBusy(true); try { const stepUp = await requestAdminStepUp(csrf); if (!stepUp) return; const response = await fetch(`${import.meta.env.REACT_API_URL}admin/currency-rates`, { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json", "xsrf-token": csrf, "x-admin-step-up": stepUp }, body: JSON.stringify({ EUR: Number(rates.EUR), USD: Number(rates.USD) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); toast.success(result.message); void loadRates(); } catch (error) { toast.error(error instanceof Error ? error.message : "Enregistrement impossible."); } finally { setBusy(false); } };
  const saveRefund = async (event: FormEvent) => { event.preventDefault(); if (!csrf) return; setBusy(true); try { const stepUp = await requestAdminStepUp(csrf); if (!stepUp) return; const response = await fetch(`${import.meta.env.REACT_API_URL}admin/finance/refunds`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "xsrf-token": csrf, "x-admin-step-up": stepUp }, body: JSON.stringify({ sourceType: refundForm.sourceType, sourceId: refundForm.sourceId, amountMGA: Number(refundForm.amount), note: refundForm.note }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); toast.success(result.message); setRefundForm({ ...refundForm, sourceId: "", amount: "", note: "" }); void loadReport(); } catch (error) { toast.error(error instanceof Error ? error.message : "Remboursement impossible."); } finally { setBusy(false); } };
  const savePayout = async (event: FormEvent, shopId: string) => { event.preventDefault(); if (!csrf) return; const draft = payoutDraft[shopId]; try { const stepUp = await requestAdminStepUp(csrf); if (!stepUp) return; const response = await fetch(`${import.meta.env.REACT_API_URL}admin/finance/seller-payouts/${shopId}`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "xsrf-token": csrf, "x-admin-step-up": stepUp }, body: JSON.stringify({ amountMGA: Number(draft?.amount), reference: draft?.reference }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); toast.success(result.message); void loadPayouts(); } catch (error) { toast.error(error instanceof Error ? error.message : "Versement impossible."); } };
  const assignRole = async (event: FormEvent, userId: string, role: StaffRole, permissions: string[]) => { event.preventDefault(); if (!csrf || !userId) return; try { const stepUp = await requestAdminStepUp(csrf); if (!stepUp) return; const response = await fetch(`${import.meta.env.REACT_API_URL}admin/staff/${userId}`, { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json", "xsrf-token": csrf, "x-admin-step-up": stepUp }, body: JSON.stringify({ role, permissions }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); toast.success("Rôle administratif enregistré."); setNewStaffId(""); void loadStaff(); } catch (error) { toast.error(error instanceof Error ? error.message : "Attribution impossible."); } };
  if (!canReadFinance) return <Navigate to="/espace_vendeur/dash" replace />;

  const cards: Array<[string, number]> = [["Encaissements", report?.grossRevenueMGA ?? 0], ["Abonnements", report?.subscriptionRevenueMGA ?? 0], ["Volume marketplace", report?.marketplacePaymentsMGA ?? 0], ["Remboursements consignés", report?.refundsMGA ?? 0], ["Net après remboursements", report?.netRevenueMGA ?? 0], ["Échéances estimées · 30 jours", report?.forecastNext30DaysMGA ?? 0]];
  const maxDaily = Math.max(1, ...(report?.byDay ?? []).map((item) => item.amountMGA));
  return <div className="space-y-5">
    <PageHeader eyebrow="Pilotage" title="Finances" description="Encaissements confirmés, remboursements consignés, soldes vendeurs et prévisions." />
    {isSuperAdmin && <section className="admin-panel p-5"><h2 className="font-bold">Taux d’affichage des devises</h2><p className="mt-1 text-sm text-[var(--admin-muted)]">Saisissez les MGA par euro et dollar. Les paiements restent en MGA. {rates.updatedAt ? `Mis à jour le ${new Date(rates.updatedAt).toLocaleString("fr-FR")}` : "Aucun taux défini."}</p><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={(event) => void saveRates(event)}><label className="text-sm">MGA pour 1 EUR<input className="admin-search-input mt-1 block" type="number" min="1" step="1" required value={rates.EUR} onChange={(event) => setRates((current) => ({ ...current, EUR: event.target.value }))} /></label><label className="text-sm">MGA pour 1 USD<input className="admin-search-input mt-1 block" type="number" min="1" step="1" required value={rates.USD} onChange={(event) => setRates((current) => ({ ...current, USD: event.target.value }))} /></label><button disabled={busy} className="admin-button admin-button--primary admin-button--md">Enregistrer les taux</button></form></section>}
    <section className="admin-panel flex flex-wrap items-end gap-3 p-4"><label className="text-sm">Du<input className="admin-search-input mt-1 block" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-sm">Au<input className="admin-search-input mt-1 block" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="admin-button admin-button--secondary admin-button--md" onClick={() => void loadReport()}>Actualiser</button></section>
    {loading ? <div className="admin-panel p-6">Calcul des indicateurs…</div> : <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, amount]) => <article key={label} className="admin-panel p-4"><p className="text-sm text-[var(--admin-muted)]">{label}</p><strong className="mt-2 block text-2xl">{money(amount)}</strong></article>)}</section><section className="admin-panel p-5"><h2 className="mb-4 font-bold">Encaissements par jour</h2>{!report?.byDay.length ? <p className="text-sm text-[var(--admin-muted)]">Aucun encaissement sur cette période.</p> : <div className="space-y-2">{report.byDay.map((item) => <div key={item.date} className="grid grid-cols-[7rem_1fr_9rem] items-center gap-3 text-xs"><span>{new Date(item.date).toLocaleDateString("fr-FR")}</span><div className="h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${Math.max(2, item.amountMGA / maxDaily * 100)}%` }} /></div><span className="text-right">{money(item.amountMGA)}</span></div>)}</div>}<p className="mt-4 text-xs text-[var(--admin-muted)]">{report?.reconciliationNote}</p></section></>}
    {canReadFinance && <section className="admin-panel p-5"><h2 className="font-bold">Soldes et reversements vendeurs</h2><p className="mt-1 text-sm text-[var(--admin-muted)]">Le registre calcule la commission configurée par boutique et le solde dû. Consigner un virement ne déclenche pas le transfert bancaire.</p><div className="mt-4 space-y-3">{payouts.map((shop) => <article key={shop._id} className="rounded-lg border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{shop.name}</strong><span>Brut {money(shop.grossMGA)} · Commission {shop.commissionPercent ?? 0}% · Solde {money(shop.balanceMGA)}</span></div>{canPayout && <form className="mt-3 flex flex-wrap gap-2" onSubmit={(event) => void savePayout(event, shop._id)}><input required className="admin-search-input" type="number" min="1" max={shop.balanceMGA} placeholder="Montant MGA" value={payoutDraft[shop._id]?.amount ?? ""} onChange={(event) => setPayoutDraft((current) => ({ ...current, [shop._id]: { ...current[shop._id], amount: event.target.value } }))} /><input required maxLength={120} className="admin-search-input" placeholder="Référence du virement" value={payoutDraft[shop._id]?.reference ?? ""} onChange={(event) => setPayoutDraft((current) => ({ ...current, [shop._id]: { ...current[shop._id], reference: event.target.value } }))} /><button className="admin-button admin-button--secondary admin-button--md">Consigner le versement</button></form>}</article>)}</div></section>}
    {canRefund && <section className="admin-panel p-5"><h2 className="font-bold">Consigner un remboursement</h2><p className="mt-1 text-sm text-[var(--admin-muted)]">Cette action met à jour le registre. Effectuez séparément le remboursement sur le moyen de paiement.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={(event) => void saveRefund(event)}><label className="text-sm">Origine<select className="admin-search-input mt-1 w-full" value={refundForm.sourceType} onChange={(event) => setRefundForm((current) => ({ ...current, sourceType: event.target.value }))}><option value="subscription">Abonnement</option><option value="marketplace">Sous-commande marketplace</option></select></label><label className="text-sm">ID source<input required className="admin-search-input mt-1 w-full" value={refundForm.sourceId} onChange={(event) => setRefundForm((current) => ({ ...current, sourceId: event.target.value }))} /></label><label className="text-sm">Montant MGA<input required type="number" min="1" step="1" className="admin-search-input mt-1 w-full" value={refundForm.amount} onChange={(event) => setRefundForm((current) => ({ ...current, amount: event.target.value }))} /></label><label className="text-sm">Motif<input required minLength={3} maxLength={500} className="admin-search-input mt-1 w-full" value={refundForm.note} onChange={(event) => setRefundForm((current) => ({ ...current, note: event.target.value }))} /></label><button disabled={busy} className="admin-button admin-button--primary admin-button--md sm:col-span-2">Enregistrer</button></form></section>}
    {isSuperAdmin && <section className="admin-panel p-5"><h2 className="font-bold">Équipe et rôles admin</h2><p className="mt-1 text-sm text-[var(--admin-muted)]">Les permissions disponibles sont bornées par rôle et contrôlées par l’API.</p><div className="mt-4 space-y-3">{staff.map((member) => { const selectedRole = staffDraft[member.userId]?.role ?? member.role; return <form key={member.userId} className="grid gap-2 rounded-lg border border-white/10 p-3 md:grid-cols-[1fr_12rem_auto]" onSubmit={(event) => void assignRole(event, member.userId, selectedRole, staffDraft[member.userId]?.permissions ?? rolePermissions[selectedRole])}><span><strong>{member.username}</strong><small className="block">{member.email}</small></span><select className="admin-search-input" value={selectedRole} onChange={(event) => { const role = event.target.value as StaffRole; setStaffDraft((current) => ({ ...current, [member.userId]: { role, permissions: rolePermissions[role] } })); }}><option>Support</option><option>Moderator</option><option>Finance</option><option>Read Only</option></select><button className="admin-button admin-button--secondary admin-button--md">Enregistrer le rôle</button></form>; })}</div><form className="mt-4 flex flex-wrap gap-2" onSubmit={(event) => void assignRole(event, newStaffId, newStaffRole, rolePermissions[newStaffRole])}><input required className="admin-search-input" placeholder="ID du compte à affecter" value={newStaffId} onChange={(event) => setNewStaffId(event.target.value)} /><select className="admin-search-input" value={newStaffRole} onChange={(event) => setNewStaffRole(event.target.value as StaffRole)}><option>Support</option><option>Moderator</option><option>Finance</option><option>Read Only</option></select><button className="admin-button admin-button--primary admin-button--md">Attribuer le rôle</button></form></section>}
    {isSuperAdmin && <section className="admin-panel flex flex-wrap items-center gap-3 p-4"><strong>Exports CSV</strong>{[["sellers", "vendeurs"], ["orders", "commandes"], ["disputes", "litiges"], ["products", "produits"], ["comments", "avis"], ["kyc", "dossiers KYC"], ["tickets", "tickets support"], ["subscriptions", "abonnements"], ["audit", "journal d’audit"]].map(([kind, label]) => <a key={kind} className="admin-button admin-button--secondary admin-button--md" href={`${import.meta.env.REACT_API_URL}admin/export?kind=${kind}`}>Exporter {label}</a>)}</section>}
  </div>;
}
