import {
  createContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";
import { useAuth } from "../helper/useAuth";

export type Language = "fr" | "en";
type Messages = Record<string, string>;

const storageKey = "shopinmada.language.v1";
const catalogs: Record<Language, Messages> = {
  fr: {
    "admin.accountSettings": "Paramètres du compte",
    "admin.accounts": "Gestion des comptes",
    "admin.addProduct": "Ajouter un produit",
    "admin.activeAccounts": "Comptes actifs",
    "admin.activeSellers": "Vendeurs actifs",
    "admin.account": "Compte",
    "admin.accountActive": "Compte actif",
    "admin.activityLog": "Journal d’activité",
    "admin.categories": "Catégories",
    "admin.closeMenu": "Fermer le menu",
    "admin.dashboard": "Tableau de bord",
    "admin.discoverPro": "Découvrir ShopInMada Pro",
    "admin.expiresOn": "Expire le",
    "admin.finance": "Finances",
    "admin.home": "Accueil",
    "admin.impersonationActive": "Assistance vendeur active · session temporaire",
    "admin.impersonationStopped": "Retour à la session administrateur.",
    "admin.impersonationStopError": "Impossible d’arrêter la session.",
    "admin.moderation": "Modération",
    "admin.confirmedSales": "Ventes confirmées",
    "admin.dashboardSellerIntro": "Suivez votre activité et traitez les commandes en attente.",
    "admin.dashboardSuperAdminIntro": "Suivez les comptes et les demandes de la plateforme.",
    "admin.greeting": "Bonjour",
    "admin.kycToReview": "Vérifications à examiner",
    "admin.manageAccounts": "Gérer les comptes",
    "admin.marketOrdersToProcess": "Commandes marketplace à traiter",
    "admin.marketplaceAdministration": "Administration de la marketplace",
    "admin.noSubscription": "Sans abonnement",
    "admin.openDisputes": "Litiges ouverts",
    "admin.openSupportTickets": "Messages support ouverts",
    "admin.ordersInProgress": "Commandes en cours",
    "admin.plansPermissions": "Forfaits et droits",
    "admin.productsToRestock": "Produits à réapprovisionner",
    "admin.shopOverview": "Pilotage de la boutique",
    "admin.settings": "Paramètres",
    "admin.sellerVerification": "Vérification vendeurs",
    "admin.signOut": "Déconnexion",
    "admin.support": "Support",
    "admin.stopImpersonation": "Arrêter l’assistance",
    "admin.deliveryPayment": "Paiement et livraison",
    "admin.disputes": "Litiges marketplace",
    "admin.marketOrders": "Commandes marketplace",
    "admin.menu": "Menu",
    "admin.orders": "Commandes",
    "admin.products": "Produits",
    "admin.professionalSpace": "Espace professionnel",
    "admin.shopInfo": "Informations de la boutique",
    "admin.subscriptionPayments": "Paiements d’abonnement",
    "admin.subscriptions": "Abonnements",
    "admin.themeDark": "sombre",
    "admin.themeLight": "clair",
    "admin.upgrade": "Passer à ShopInMada Pro",
    "admin.viewOrders": "Voir les commandes",
    "cart.address": "Adresse",
    "cart.amountDue": "Vous paierez {amount} à la boutique {shop}.",
    "cart.checkoutError": "Une erreur est survenue.",
    "cart.checkoutFailed": "Impossible de valider la commande.",
    "cart.chooseAddress": "Choisir…",
    "cart.choosePayment": "Choisir un mode de paiement",
    "cart.choosePaymentPerShop": "Choisissez un mode de paiement pour chaque boutique.",
    "cart.city": "Ville",
    "cart.configurePayment": "Cette boutique doit configurer ses modes de paiement avant de recevoir une commande.",
    "cart.customerDetails": "Vos coordonnées",
    "cart.decreaseQuantity": "Diminuer la quantité",
    "cart.delivery": "Livraison",
    "cart.emailOptional": "E-mail (facultatif)",
    "cart.empty": "Votre panier est vide",
    "cart.emptyButton": "Vider le panier",
    "cart.explore": "Explorez nos boutiques pour découvrir ce qui vous intéresse.",
    "cart.guestCheckout": "La commande peut être passée sans compte client.",
    "cart.increaseQuantity": "Augmenter la quantité",
    "cart.itemsLabel": "Articles par boutique",
    "cart.loadingPayment": "Chargement des modes de paiement…",
    "cart.multiVendorNote": "Chaque boutique recevra et traitera sa propre sous-commande. Vous paierez directement chaque vendeur selon le mode sélectionné.",
    "cart.name": "Nom",
    "cart.notConfigured": "À configurer",
    "cart.optionalEmail": "E-mail (facultatif)",
    "cart.orderSent": "Commande envoyée aux boutiques.",
    "cart.paymentLoadError": "Impossible de charger les modes de paiement.",
    "cart.paymentMethodsUnavailable": "Modes de paiement indisponibles.",
    "cart.paymentSetupRequired": "Cette boutique doit configurer ses modes de paiement avant de recevoir une commande.",
    "cart.paymentUnavailable": "Modes de paiement indisponibles",
    "cart.phone": "Téléphone",
    "cart.removeItem": "Retirer {name}",
    "cart.selection": "Votre sélection",
    "cart.shop": "Boutique",
    "cart.shopAmountUnknown": "le montant communiqué par la boutique",
    "cart.subtotal": "Sous-total",
    "cart.title": "Panier et validation",
    "cart.useSavedAddress": "Utiliser une adresse enregistrée",
    "comment.add": "Ajouter un commentaire",
    "comment.countLabel": "commentaires",
    "comment.emptyHint": "Partagez votre expérience et soyez le premier à donner votre avis.",
    "comment.emptyTitle": "Aucun commentaire pour le moment",
    "comment.loginRequired": "Vous devez vous connecter d’abord.",
    "comment.placeholder": "Qu’avez-vous pensé de ce produit ?",
    "comment.sendError": "Impossible d’envoyer le commentaire.",
    "comment.submit": "Envoyer le commentaire",
    "comment.title": "Commentaires",
    "comment.verifiedBuyer": "Acheteur vérifié",
    "comment.yourOpinion": "Votre avis compte",
    "language.english": "Anglais",
    "language.french": "Français",
    "language.label": "Langue",
    "language.saveError": "Impossible d’enregistrer la langue sur votre compte. Votre choix précédent a été rétabli.",
    "nav.about": "À propos",
    "nav.account": "Mon compte",
    "nav.allCities": "Toutes les villes",
    "nav.becomeSeller": "Devenir vendeur",
    "nav.categories": "Catégories",
    "nav.contact": "Contact",
    "nav.discover": "Découvrir",
    "nav.exploreProducts": "Explorer les produits",
    "nav.joinSellers": "Vous êtes vendeur ? Rejoignez-nous",
    "nav.localMarket": "Des boutiques locales, partout à Madagascar",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "nav.proOffer": "Offre Pro",
    "nav.register": "Créer un compte",
    "nav.registerShort": "Inscription",
    "nav.search": "Rechercher",
    "nav.searchDesktop": "Que recherchez-vous aujourd’hui ?",
    "nav.searchMobile": "Rechercher un produit...",
    "nav.sell": "Vendre",
    "nav.sellerSpace": "Mon espace",
    "product.addFavorite": "♡ Ajouter aux favoris",
    "product.addedToCart": "Article ajouté au panier.",
    "product.chooseOption": "Choisir une option",
    "product.details": "Détails du produit",
    "product.favoriteUnavailable": "Favoris indisponibles.",
    "product.favoriteAdded": "Ajouté à vos favoris.",
    "product.favoriteRemoved": "Retiré de vos favoris.",
    "product.gallery": "Galerie photos du produit",
    "product.imageUnavailable": "Image indisponible",
    "product.loadError": "Une erreur est survenue.",
    "product.loginForFavorites": "Connectez-vous pour enregistrer vos favoris.",
    "product.quantities": "Quantités",
    "product.recentlyViewed": "Consultés récemment",
    "product.removeFavorite": "♥ Retirer des favoris",
    "product.showPhoto": "Afficher la photo {number}",
    "product.soldBy": "Vendu par",
    "product.stockExceeded": "La quantité dépasse le stock disponible.",
    "product.totalEstimate": "Total estimé",
    "product.viewRecent": "Revoir un produit consulté",
    "profile.accountInfo": "Informations du compte",
    "profile.addAddress": "Ajouter cette adresse",
    "profile.address": "Adresse",
    "profile.addressLabel": "Libellé (Maison)",
    "profile.addresses": "Adresses de livraison",
    "profile.addressesHint": "Enregistrez vos coordonnées pour vos prochaines commandes.",
    "profile.changePassword": "Changer le mot de passe",
    "profile.city": "Ville",
    "profile.close": "Fermer",
    "profile.completeHint": "Complétez vos coordonnées pour faciliter vos achats et vos livraisons.",
    "profile.completed": "Profil complété",
    "profile.conversionUnavailable": "Conversion momentanément indisponible; les montants restent affichés en MGA.",
    "profile.currency": "Devise",
    "profile.currentSession": "Session actuelle",
    "profile.delete": "Supprimer",
    "profile.description": "Gérez votre identité, votre sécurité et les informations utiles à vos achats et à votre boutique.",
    "profile.edit": "Modifier mes informations",
    "profile.exchangeDate": "Taux indicatif mis à jour le {date}. Les paiements restent en MGA.",
    "profile.exportData": "Exporter mes données",
    "profile.exportDescription": "Export de vos informations personnelles",
    "profile.favorites": "Favoris",
    "profile.female": "Femme",
    "profile.firstName": "Prénom",
    "profile.fullAddress": "Adresse complète",
    "profile.gender": "Sexe",
    "profile.languageSpace": "Langue de votre espace",
    "profile.male": "Homme",
    "profile.marketplaceMessages": "Messages marketplace",
    "profile.name": "Nom",
    "profile.noFavorites": "Aucun favori enregistré.",
    "profile.noRecentlyViewed": "Aucun produit consulté récemment.",
    "profile.notProvided": "Non renseignée",
    "profile.notProvidedMasc": "Non renseigné",
    "profile.notificationHint": "Gérez vos alertes et préférences",
    "profile.notifications": "Notifications",
    "profile.openShop": "Ouvrir une boutique",
    "profile.orderAlerts": "Commandes et livraisons",
    "profile.personalInfo": "Coordonnées personnelles",
    "profile.personalModal": "Mon profil",
    "profile.personalModalHint": "Quelques détails pour compléter votre espace ShopInMada.",
    "profile.personalModalTitle": "Informations personnelles",
    "profile.phone": "Téléphone",
    "profile.phoneExample": "Ex. 034 00 000 00",
    "profile.phoneNumber": "Numéro de téléphone",
    "profile.preferences": "Préférences",
    "profile.privacy": "Confidentialité",
    "profile.products": "Vos produits",
    "profile.productsHint": "Retrouvez vos favoris et vos découvertes récentes.",
    "profile.promotionAlerts": "Promotions et bons",
    "profile.provided": "Renseignée",
    "profile.providedMasc": "Renseigné",
    "profile.recentlyViewed": "Consultés récemment",
    "profile.recipient": "Nom du destinataire",
    "profile.remove": "Retirer",
    "profile.save": "Enregistrer",
    "profile.saving": "Enregistrement…",
    "profile.security": "Sécurité",
    "profile.securityHint": "Mot de passe, sessions et vigilance",
    "profile.sendCode": "Envoi du code…",
    "profile.signOut": "Se déconnecter",
    "profile.title": "Profil et coordonnées",
    "profile.toComplete": "À compléter",
    "profile.upToDate": "Vos coordonnées sont à jour.",
    "seller.address": "Adresse",
    "seller.addressExample": "Ville, quartier, adresse",
    "seller.brandAnywhere": "Votre marque, partout.",
    "seller.categoriesLoadError": "Erreur lors du chargement des catégories.",
    "seller.categoryHint": "Choisissez les catégories qui représentent le mieux vos produits.",
    "seller.contactHint": "Ces informations aideront vos clients à vous trouver et à vous contacter.",
    "seller.createWorkspace": "Créez votre espace vendeur",
    "seller.dropLogo": "Déposez votre logo ici",
    "seller.email": "Adresse e-mail",
    "seller.emailExample": "contact@votreboutique.mg",
    "seller.exampleShop": "Ex. Atelier Mada",
    "seller.genericError": "Une erreur s'est produite.",
    "seller.heroDescription": "Rejoignez ShopInMada et présentez vos produits aux clients partout à Madagascar.",
    "seller.heroTitle": "Votre boutique mérite une vitrine remarquable.",
    "seller.invalidLogo": "Le logo doit être au format JPG, PNG ou WebP et peser 5 Mo maximum.",
    "seller.logo": "Logo de la boutique",
    "seller.logoBrowse": "Formats image · Cliquez pour parcourir",
    "seller.onboardingDescription": "Quelques informations suffisent pour préparer votre boutique en ligne.",
    "seller.optional": "Facultatif",
    "seller.phone": "Téléphone",
    "seller.phoneExample": "Ex. 034 12 345 67",
    "seller.presentActivity": "Présentez votre activité",
    "seller.requiredFields": "Renseignez les coordonnées, le logo et au moins une catégorie.",
    "seller.selectCategories": "Sélectionnez vos catégories",
    "seller.shopInformation": "Informations de la boutique",
    "seller.shopName": "Nom de la boutique",
    "seller.startTogether": "Commençons ensemble",
    "seller.step": "Étape 1 sur 1",
    "seller.stepCategories": "02 · Ajoutez vos catégories",
    "seller.stepCustomers": "03 · Touchez de nouveaux clients",
    "seller.stepStorefront": "01 · Créez votre vitrine",
    "seller.storefront": "Votre vitrine",
    "seller.storefrontGrowth": "Une vitrine pensée pour grandir",
    "seller.submit": "Soumettre ma boutique",
    "seller.submitError": "Échec de la création de la boutique.",
    "seller.submitHint": "En envoyant ce formulaire, vous soumettez votre boutique à validation.",
    "seller.submitting": "Envoi en cours…",
    "seller.taxId": "NIF / STAT",
    "seller.taxReference": "Vos références administratives",
    "verify.accountValidation": "Validation de votre compte",
    "verify.accountVerified": "Compte vérifié avec succès !",
    "verify.addressVerified": "Adresse vérifiée. Choisissez un nouveau mot de passe.",
    "verify.codeDigit": "Chiffre {number} du code",
    "verify.codeRequired": "Veuillez entrer le code complet.",
    "verify.connectionError": "Une erreur est survenue. Veuillez vérifier votre connexion.",
    "verify.emailCodeHint": "Si un compte correspond à l’adresse saisie, un code à 6 chiffres a été envoyé par e-mail.",
    "verify.enterCode": "Entrez votre code de sécurité.",
    "verify.expiryHint": "Pour votre sécurité, le code expire après un court délai.",
    "verify.invalidCode": "Le code est invalide, expiré ou indisponible. Vérifiez votre e-mail et réessayez.",
    "verify.passwordRecovery": "Récupération du mot de passe",
    "verify.pasteHint": "Vous pouvez coller le code complet.",
    "verify.secureConnection": "Connexion sécurisée",
    "verify.securityError": "Erreur de sécurité. Veuillez réessayer.",
    "verify.stepProgress": "Étape 2 sur 2",
    "verify.submit": "Valider mon compte",
    "verify.submitting": "Validation…",
  },
  en: {
    "admin.accountSettings": "Account settings",
    "admin.accounts": "Account management",
    "admin.addProduct": "Add a product",
    "admin.activeAccounts": "Active accounts",
    "admin.activeSellers": "Active sellers",
    "admin.account": "Account",
    "admin.accountActive": "Account active",
    "admin.activityLog": "Activity log",
    "admin.categories": "Categories",
    "admin.closeMenu": "Close menu",
    "admin.dashboard": "Dashboard",
    "admin.discoverPro": "Discover ShopInMada Pro",
    "admin.expiresOn": "Expires",
    "admin.finance": "Finance",
    "admin.home": "Home",
    "admin.impersonationActive": "Seller support active · temporary session",
    "admin.impersonationStopped": "Back to the administrator session.",
    "admin.impersonationStopError": "Unable to stop the session.",
    "admin.moderation": "Moderation",
    "admin.confirmedSales": "Confirmed sales",
    "admin.dashboardSellerIntro": "Track your activity and process pending orders.",
    "admin.dashboardSuperAdminIntro": "Track platform accounts and requests.",
    "admin.greeting": "Hello",
    "admin.kycToReview": "Verifications to review",
    "admin.manageAccounts": "Manage accounts",
    "admin.marketOrdersToProcess": "Marketplace orders to process",
    "admin.marketplaceAdministration": "Marketplace administration",
    "admin.noSubscription": "No subscription",
    "admin.openDisputes": "Open disputes",
    "admin.openSupportTickets": "Open support tickets",
    "admin.ordersInProgress": "Orders in progress",
    "admin.plansPermissions": "Plans and permissions",
    "admin.productsToRestock": "Products to restock",
    "admin.shopOverview": "Shop overview",
    "admin.settings": "Settings",
    "admin.sellerVerification": "Seller verification",
    "admin.signOut": "Sign out",
    "admin.support": "Support",
    "admin.stopImpersonation": "Stop support session",
    "admin.deliveryPayment": "Payment and delivery",
    "admin.disputes": "Marketplace disputes",
    "admin.marketOrders": "Marketplace orders",
    "admin.menu": "Menu",
    "admin.orders": "Orders",
    "admin.products": "Products",
    "admin.professionalSpace": "Business workspace",
    "admin.shopInfo": "Shop information",
    "admin.subscriptionPayments": "Subscription payments",
    "admin.subscriptions": "Subscriptions",
    "admin.themeDark": "dark",
    "admin.themeLight": "light",
    "admin.upgrade": "Upgrade to ShopInMada Pro",
    "admin.viewOrders": "View orders",
    "cart.address": "Address",
    "cart.amountDue": "You will pay {amount} to {shop}.",
    "cart.checkout": "Place orders",
    "cart.checkoutError": "Something went wrong.",
    "cart.checkoutFailed": "Unable to validate the order.",
    "cart.chooseAddress": "Choose…",
    "cart.choosePayment": "Choose a payment method",
    "cart.choosePaymentPerShop": "Choose a payment method for each shop.",
    "cart.city": "City",
    "cart.configurePayment": "This shop must configure its payment methods before receiving an order.",
    "cart.customerDetails": "Your details",
    "cart.decreaseQuantity": "Decrease quantity",
    "cart.delivery": "Delivery",
    "cart.emailOptional": "Email (optional)",
    "cart.empty": "Your cart is empty",
    "cart.emptyButton": "Empty cart",
    "cart.explore": "Explore our shops to find what interests you.",
    "cart.guestCheckout": "You can place an order without an account.",
    "cart.increaseQuantity": "Increase quantity",
    "cart.itemsLabel": "Items by shop",
    "cart.loadingPayment": "Loading payment methods…",
    "cart.multiVendorNote": "Each shop will receive and process its own sub-order. You'll pay each seller directly based on the selected method.",
    "cart.name": "Name",
    "cart.notConfigured": "Not configured",
    "cart.optionalEmail": "Email (optional)",
    "cart.orderSent": "Order sent to shops.",
    "cart.paymentLoadError": "Unable to load payment methods.",
    "cart.paymentMethodsUnavailable": "Payment methods unavailable.",
    "cart.paymentSetupRequired": "This shop must configure its payment methods before receiving an order.",
    "cart.paymentUnavailable": "Payment methods unavailable",
    "cart.phone": "Phone",
    "cart.removeItem": "Remove {name}",
    "cart.selection": "Your selection",
    "cart.shop": "Shop",
    "cart.shopAmountUnknown": "the amount communicated by the shop",
    "cart.submitting": "Submitting…",
    "cart.subtotal": "Subtotal",
    "cart.title": "Your cart and checkout",
    "cart.useSavedAddress": "Use a saved address",
    "comment.add": "Add a comment",
    "comment.countLabel": "comments",
    "comment.emptyHint": "Share your experience and be the first to leave a review.",
    "comment.emptyTitle": "No comments yet",
    "comment.loginRequired": "Please sign in first.",
    "comment.placeholder": "What did you think of this product?",
    "comment.sendError": "Unable to send the comment.",
    "comment.submit": "Send comment",
    "comment.title": "Comments",
    "comment.verifiedBuyer": "Verified buyer",
    "comment.yourOpinion": "Your opinion matters",
    "language.english": "English",
    "language.french": "French",
    "language.label": "Language",
    "language.saveError": "Could not save the language to your account. Your previous choice has been restored.",
    "nav.about": "About",
    "nav.account": "My account",
    "nav.allCities": "All cities",
    "nav.becomeSeller": "Become a seller",
    "nav.categories": "Categories",
    "nav.contact": "Contact",
    "nav.discover": "Discover",
    "nav.exploreProducts": "Explore products",
    "nav.joinSellers": "Are you a seller? Join us",
    "nav.localMarket": "Local shops across Madagascar",
    "nav.login": "Sign in",
    "nav.logout": "Sign out",
    "nav.proOffer": "Pro plan",
    "nav.register": "Create an account",
    "nav.registerShort": "Register",
    "nav.search": "Search",
    "nav.searchDesktop": "What are you looking for today?",
    "nav.searchMobile": "Search for a product...",
    "nav.sell": "Sell",
    "nav.sellerSpace": "My workspace",
    "product.addFavorite": "♡ Add to favorites",
    "product.addedToCart": "Item added to cart.",
    "product.chooseOption": "Choose an option",
    "product.details": "Product details",
    "product.favoriteUnavailable": "Favorites unavailable.",
    "product.favoriteAdded": "Added to favorites.",
    "product.favoriteRemoved": "Removed from favorites.",
    "product.gallery": "Product photo gallery",
    "product.imageUnavailable": "Image unavailable",
    "product.loadError": "An error occurred.",
    "product.loginForFavorites": "Sign in to save favorites.",
    "product.quantities": "Quantity",
    "product.recentlyViewed": "Recently viewed",
    "product.removeFavorite": "♥ Remove from favorites",
    "product.showPhoto": "Show photo {number}",
    "product.soldBy": "Sold by",
    "product.stockExceeded": "The quantity exceeds available stock.",
    "product.totalEstimate": "Estimated total",
    "product.viewRecent": "View a recently viewed product",
    "profile.accountInfo": "Account information",
    "profile.addAddress": "Add this address",
    "profile.address": "Address",
    "profile.addressLabel": "Label (Home)",
    "profile.addresses": "Delivery addresses",
    "profile.addressesHint": "Save your details for future orders.",
    "profile.changePassword": "Change password",
    "profile.city": "City",
    "profile.close": "Close",
    "profile.completeHint": "Complete your details to make shopping and delivery easier.",
    "profile.completed": "Profile completed",
    "profile.conversionUnavailable": "Conversion is temporarily unavailable; amounts remain in MGA.",
    "profile.currency": "Currency",
    "profile.currentSession": "Current session",
    "profile.delete": "Delete",
    "profile.description": "Manage your identity, security, and information for shopping and your shop.",
    "profile.edit": "Edit my information",
    "profile.exchangeDate": "Indicative rate updated on {date}. Payments remain in MGA.",
    "profile.exportData": "Export my data",
    "profile.exportDescription": "Export your personal information",
    "profile.favorites": "Favorites",
    "profile.female": "Female",
    "profile.firstName": "First name",
    "profile.fullAddress": "Full address",
    "profile.gender": "Gender",
    "profile.languageSpace": "Workspace language",
    "profile.male": "Male",
    "profile.marketplaceMessages": "Marketplace messages",
    "profile.name": "Last name",
    "profile.noFavorites": "No saved favorites.",
    "profile.noRecentlyViewed": "No recently viewed products.",
    "profile.notProvided": "Not provided",
    "profile.notProvidedMasc": "Not provided",
    "profile.notificationHint": "Manage your alerts and preferences",
    "profile.notifications": "Notifications",
    "profile.openShop": "Open a shop",
    "profile.orderAlerts": "Orders and delivery",
    "profile.personalInfo": "Personal details",
    "profile.personalModal": "My profile",
    "profile.personalModalHint": "A few details to complete your ShopInMada profile.",
    "profile.personalModalTitle": "Personal information",
    "profile.phone": "Phone",
    "profile.phoneExample": "e.g. 034 00 000 00",
    "profile.phoneNumber": "Phone number",
    "profile.preferences": "Preferences",
    "profile.privacy": "Privacy",
    "profile.products": "Your products",
    "profile.productsHint": "Find your favorites and recent discoveries.",
    "profile.promotionAlerts": "Promotions and vouchers",
    "profile.provided": "Provided",
    "profile.providedMasc": "Provided",
    "profile.recentlyViewed": "Recently viewed",
    "profile.recipient": "Recipient name",
    "profile.remove": "Remove",
    "profile.save": "Save",
    "profile.saving": "Saving…",
    "profile.security": "Security",
    "profile.securityHint": "Password, sessions, and account safety",
    "profile.sendCode": "Sending code…",
    "profile.signOut": "Sign out",
    "profile.title": "Profile and contact details",
    "profile.toComplete": "Not provided",
    "profile.upToDate": "Your details are up to date.",
    "seller.address": "Address",
    "seller.addressExample": "City, neighborhood, address",
    "seller.brandAnywhere": "Your brand, everywhere.",
    "seller.categoriesLoadError": "Unable to load categories.",
    "seller.categoryHint": "Choose the categories that best represent your products.",
    "seller.contactHint": "This information helps customers find and contact you.",
    "seller.createWorkspace": "Create your seller workspace",
    "seller.dropLogo": "Drop your logo here",
    "seller.email": "Email address",
    "seller.emailExample": "contact@yourshop.mg",
    "seller.exampleShop": "e.g. Atelier Mada",
    "seller.genericError": "Something went wrong.",
    "seller.heroDescription": "Join ShopInMada and showcase your products to customers across Madagascar.",
    "seller.heroTitle": "Your shop deserves a remarkable storefront.",
    "seller.invalidLogo": "The logo must be JPG, PNG, or WebP and no larger than 5 MB.",
    "seller.logo": "Shop logo",
    "seller.logoBrowse": "Image formats · Click to browse",
    "seller.onboardingDescription": "A few details are all you need to prepare your online shop.",
    "seller.optional": "Optional",
    "seller.phone": "Phone",
    "seller.phoneExample": "e.g. 034 12 345 67",
    "seller.presentActivity": "Tell us about your business",
    "seller.requiredFields": "Enter your contact details, logo, and at least one category.",
    "seller.selectCategories": "Select your categories",
    "seller.shopInformation": "Shop information",
    "seller.shopName": "Shop name",
    "seller.startTogether": "Let’s get started",
    "seller.step": "Step 1 of 1",
    "seller.stepCategories": "02 · Add your categories",
    "seller.stepCustomers": "03 · Reach new customers",
    "seller.stepStorefront": "01 · Create your storefront",
    "seller.storefront": "Your storefront",
    "seller.storefrontGrowth": "A storefront designed to grow",
    "seller.submit": "Submit my shop",
    "seller.submitError": "Unable to create the shop.",
    "seller.submitHint": "Submitting this form sends your shop for approval.",
    "seller.submitting": "Submitting…",
    "seller.taxId": "Tax ID / STAT",
    "seller.taxReference": "Your business registration details",
    "verify.accountValidation": "Account verification",
    "verify.accountVerified": "Account verified successfully!",
    "verify.addressVerified": "Address verified. Choose a new password.",
    "verify.codeDigit": "Code digit {number}",
    "verify.codeRequired": "Please enter the full code.",
    "verify.connectionError": "Something went wrong. Check your connection.",
    "verify.emailCodeHint": "If an account matches the address provided, a 6-digit code has been sent by email.",
    "verify.enterCode": "Enter your security code.",
    "verify.expiryHint": "For your security, the code expires shortly.",
    "verify.invalidCode": "The code is invalid, expired, or unavailable. Check your email and try again.",
    "verify.passwordRecovery": "Password recovery",
    "verify.pasteHint": "You can paste the full code.",
    "verify.secureConnection": "Secure connection",
    "verify.securityError": "Security error. Please try again.",
    "verify.stepProgress": "Step 2 of 2",
    "verify.submit": "Verify my account",
    "verify.submitting": "Verifying…",
  },
};

const translationBundles: Record<Language, Record<string, string>> = {
  fr: {
    "auth.alreadyAccount": "Déjà un compte ?",
    "auth.back": "Retour",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.email": "Votre email",
    "auth.emailOrPhone": "Adresse e-mail ou téléphone",
    "auth.emailPlaceholder": "Votre email",
    "auth.emailTitle": "Entrer votre Email",
    "auth.forgotPassword": "Mot de passe oublié",
    "auth.loginIntro": "Connectez-vous à votre espace ShopInMada.",
    "auth.name": "Votre nom",
    "auth.newPassword": "Nouveau mot de passe",
    "auth.noAccount": "Pas encore de compte ?",
    "auth.password": "Mot de passe",
    "auth.passwordMismatch": "Les mots de passe ne correspondent pas !",
    "auth.phone": "Numéro de téléphone",
    "auth.register": "S'inscrire",
    "auth.registerTitle": "Créer un compte",
    "auth.reset": "Réinitialiser",
    "auth.resetSuccess": "Mot de passe réinitialisé avec succès !",
    "auth.resetTitle": "Réinitialiser le mot de passe",
    "auth.sending": "Envoi en cours...",
    "auth.serverError": "Une erreur est survenue.",
    "auth.signIn": "Se connecter",
    "auth.submit": "Soumettre",
    "auth.wait": "Veuillez patienter",
    "auth.welcomeBack": "Bon retour",
    "cart.checkout": "Confirmer les commandes",
    "cart.submitting": "Envoi en cours…",
    "contact.address": "Notre adresse",
    "contact.addressText": "Au service du commerce local, partout dans le pays.",
    "contact.call": "Appelez-nous",
    "contact.email": "Adresse e-mail",
    "contact.formIntro": "Remplissez les champs ci-dessous pour nous écrire.",
    "contact.formTitle": "Envoyez-nous un message",
    "contact.intro": "Une question sur ShopInMada ? Notre équipe est disponible pour vous aider.",
    "contact.kicker": "Restons en contact",
    "contact.message": "Votre message",
    "contact.messageExample": "Décrivez votre demande…",
    "contact.name": "Votre nom",
    "contact.nameExample": "Ex. Rakoto Jean",
    "contact.phoneText": "Nous serons ravis d’échanger avec vous.",
    "contact.sendError": "Impossible d’envoyer le message.",
    "contact.sending": "Envoi en cours…",
    "contact.subject": "Sujet",
    "contact.subjectExample": "Comment pouvons-nous vous aider ?",
    "contact.submit": "Envoyer le message",
    "contact.title": "Parlons de votre projet.",
    "footer.about": "À propos",
    "footer.contact": "Nous contacter",
    "footer.pro": "Offre Pro",
    "footer.rights": "Tous droits réservés.",
    "footer.tagline": "La marketplace locale de Madagascar",
    "home.buyLocal": "Achetez local",
    "home.byCity": "Explorez les offres par ville et par boutique.",
    "home.curated": "Sélectionnées pour vous",
    "home.discoveryText": "Trouvez ce qu’il vous faut et entrez directement en contact avec les boutiques.",
    "home.discoveryTitle": "Tout commence par une belle découverte.",
    "home.everywhere": "Partout au pays",
    "home.exploreRegions": "Explorez par région",
    "home.exploreRegionsText": "Affinez votre recherche avec les villes disponibles dans la marketplace.",
    "home.featureAnalytics": "Statistiques avancées",
    "home.featureListings": "Annonces illimitées",
    "home.featurePromotions": "Promotions exclusives",
    "home.featureSearch": "Mise en avant dans les recherches",
    "home.featureStorePage": "Page boutique personnalisée",
    "home.featureSupport": "Support prioritaire",
    "home.forProfessionals": "Pour les professionnels",
    "home.growShops": "Faites grandir nos boutiques",
    "home.heroAlt": "Illustration d'un sac de shopping ShopInMada entouré de produits",
    "home.intro": "Explorez des produits uniques et soutenez les boutiques de Madagascar. Votre prochaine belle découverte est ici.",
    "home.kicker": "Le commerce malgache, à portée de clic",
    "home.localFinds": "Les pépites du pays",
    "home.localShops": "Boutiques locales",
    "home.localShopsText": "Une place pour les petites entreprises et les marques locales.",
    "home.localShopsTitle": "Des boutiques malgaches",
    "home.meetShops": "Rencontrez les boutiques",
    "home.meetShopsText": "Consultez les produits et les informations partagées par chaque vendeur.",
    "home.noProducts": "Les produits arrivent bientôt.",
    "home.perMonth": "/ mois",
    "home.planAdvancedAnalytics": "Statistiques avancées",
    "home.planCustomCategories": "Catégories personnalisées",
    "home.planLoading": "Chargement du tarif…",
    "home.planMaxProducts": "Jusqu’à {count} produits",
    "home.planPrioritySupport": "Support prioritaire",
    "home.planUnavailable": "Tarif indisponible pour le moment",
    "home.planUnlimited": "Produits illimités",
    "home.popularProducts": "Les nouveautés",
    "home.proDescription": "Des outils pour mettre en valeur votre catalogue et gérer votre activité.",
    "home.proSlogan": "Votre boutique, en première ligne.",
    "home.proText": "Développez votre présence en ligne et présentez vos produits à de nouveaux clients sur ShopInMada.",
    "home.proTitle": "Donnez plus de visibilité à votre boutique.",
    "home.productLoadError": "Impossible de charger les produits.",
    "home.productsForAll": "Des produits pour tous",
    "home.search": "Un produit, une boutique, une idée...",
    "home.searchEasy": "Recherchez facilement",
    "home.searchEasyText": "Parcourez le catalogue ou recherchez un article précis en quelques secondes.",
    "home.selection": "Sélection du moment",
    "home.simpleExperience": "Une expérience simple",
    "home.startSelling": "Commencer maintenant",
    "home.storyKicker": "Une marketplace d’ici",
    "home.storyLink": "Découvrir la marketplace",
    "home.storyText": "ShopInMada rapproche les boutiques malgaches et les personnes qui recherchent des produits uniques. Découvrez, échangez avec les vendeurs et faites vivre le commerce local.",
    "home.storyTitle": "Le savoir-faire malgache mérite une vitrine sans frontières.",
    "home.supportLocal": "Un achat qui soutient",
    "home.supportText": "Chaque découverte fait rayonner le talent local.",
    "home.title": "Les trouvailles locales",
    "home.titleAccent": "qui font la différence.",
    "home.viewAll": "Voir toute la boutique",
    "nav.mobileAccount": "Compte",
    "nav.mobileCart": "Panier",
    "nav.mobileExplore": "Explorer",
    "nav.mobileHome": "Accueil",
    "nav.mobileNavigation": "Navigation mobile",
    "nav.mobileSell": "Vendre",
    "order.accountReference": "Référence du compte",
    "order.beneficiary": "Bénéficiaire",
    "order.cancel": "Annuler",
    "order.cancelSuborder": "Annuler cette sous-commande",
    "order.carrier": "Transporteur",
    "order.checkingItems": "Vérification des articles…",
    "order.confirmReceipt": "Confirmer la réception",
    "order.continueShopping": "Continuer mes achats",
    "order.date": "Commande du",
    "order.declarePayment": "Déclarer le paiement",
    "order.declaredReference": "Référence déclarée",
    "order.delivery": "Livraison",
    "order.expiration": "expiration du délai",
    "order.follow": "Suivre cette commande",
    "order.guestLinkHint": "Ouvrez le lien de suivi complet reçu après validation de la commande.",
    "order.historyTitle": "Historique des commandes marketplace",
    "order.iPaid": "J’ai payé, déclarer",
    "order.method": "Mode",
    "order.noOrders": "Aucune commande multi-vendeur pour le moment.",
    "order.notFound": "Commande introuvable.",
    "order.paySeller": "Payer directement le vendeur",
    "order.payment": "Paiement",
    "order.payment.confirmed": "confirmé",
    "order.payment.declared": "déclaré",
    "order.payment.due": "à effectuer",
    "order.paymentMethod.airtel_money": "Airtel Money",
    "order.paymentMethod.mvola": "MVola",
    "order.paymentMethod.orange_money": "Orange Money",
    "order.paymentMethod.paiement_livraison": "Paiement à la livraison",
    "order.paymentMethod.virement": "Virement bancaire",
    "order.phoneAccount": "Téléphone / compte",
    "order.refunded": "Remboursé",
    "order.repeat": "Recommander",
    "order.reportDispute": "Signaler un litige",
    "order.screenshotOptional": "Capture d’écran (facultative)",
    "order.sellerAccept": "Le vendeur doit accepter votre demande avant le",
    "order.sellerMustConfirm": "Le vendeur doit confirmer la réception des fonds.",
    "order.shop": "Boutique",
    "order.shopCountPlural": "{count} boutiques",
    "order.shopCountSingle": "{count} boutique",
    "order.status.annulee": "Annulée",
    "order.status.en_attente_paiement": "Paiement à effectuer",
    "order.status.en_attente_vendeur": "En attente de réponse du vendeur",
    "order.status.en_preparation": "En préparation",
    "order.status.expediee": "Expédiée",
    "order.status.expiree": "Expirée",
    "order.status.litige": "En litige",
    "order.status.livree": "Livrée",
    "order.status.paiement_confirme": "Paiement confirmé",
    "order.status.paiement_declare": "Paiement déclaré, en vérification",
    "order.status.partiellement_terminee": "Partiellement terminée",
    "order.status.refusee": "Refusée",
    "order.status.terminee": "Terminée",
    "order.statusHistory": "Historique des changements",
    "order.suborder": "Sous-commande",
    "order.subtotal": "Sous-total boutique",
    "order.toPay": "À payer à {shop}",
    "order.tracking": "Suivi de commande",
    "order.trackingNumber": "Suivi",
    "order.transactionReference": "Référence de transaction",
    "order.viewEvidence": "Voir la capture envoyée",
    "order.yourOrder": "Votre commande",
    "product.addToCart": "Ajouter au panier",
    "product.notFound": "Ce produit n’existe pas ou n’est plus publié.",
    "product.outOfStock": "Rupture de stock",
    "product.unavailable": "Produit indisponible",
    "shop.allCities": "Toutes les villes",
    "shop.allProducts": "Tous les produits",
    "shop.applyFilters": "Appliquer les filtres",
    "shop.categories": "Catégories",
    "shop.categoryLoadError": "Impossible de charger les catégories pour le moment.",
    "shop.categoryLabel": "Catégorie",
    "shop.categoryTitle": "Produits de cette catégorie",
    "shop.city": "Ville",
    "shop.closeCategories": "Fermer les catégories",
    "shop.collapseCategories": "Réduire les catégories",
    "shop.explore": "Explorer",
    "shop.hideSubcategories": "Masquer les sous-catégories de",
    "shop.loadError": "Impossible de charger les produits.",
    "shop.loading": "Chargement des produits…",
    "shop.loadingCategories": "Chargement des catégories…",
    "shop.maximumPrice": "Prix maximum (MGA)",
    "shop.minimumPrice": "Prix minimum (MGA)",
    "shop.newest": "Plus récents",
    "shop.next": "Suivant",
    "shop.noMaximum": "Aucun maximum",
    "shop.noMinimum": "Aucun minimum",
    "shop.noResults": "Aucun produit ne correspond à votre recherche.",
    "shop.noResultsHint": "Essayez une autre recherche ou explorez toutes les catégories.",
    "shop.otherProducts": "Autres produits",
    "shop.of": "sur",
    "shop.oldest": "Plus anciens",
    "shop.pageOf": "Page",
    "shop.pageProductCount": "{count} sur cette page",
    "shop.pagination": "Pagination des produits",
    "shop.previous": "Précédent",
    "shop.priceAscending": "Prix croissant",
    "shop.priceDescending": "Prix décroissant",
    "shop.productCount": "{count} produit(s)",
    "shop.resultsFor": "Résultats pour",
    "shop.showCategories": "Afficher les catégories",
    "shop.showSubcategories": "Afficher les sous-catégories de",
    "shop.sortBy": "Trier par",
    "shop.storeTitle": "Explorez cette boutique",
    "shop.title": "Tous les produits",
  },
  en: {
    "auth.alreadyAccount": "Already have an account?",
    "auth.back": "Back",
    "auth.confirmPassword": "Confirm password",
    "auth.email": "Your email",
    "auth.emailOrPhone": "Email address or phone",
    "auth.emailPlaceholder": "Your email",
    "auth.emailTitle": "Enter your email",
    "auth.forgotPassword": "Forgot password?",
    "auth.loginIntro": "Sign in to your ShopInMada account.",
    "auth.name": "Your name",
    "auth.newPassword": "New password",
    "auth.noAccount": "Don't have an account?",
    "auth.password": "Password",
    "auth.passwordMismatch": "Passwords do not match!",
    "auth.phone": "Phone number",
    "auth.register": "Sign up",
    "auth.registerTitle": "Create an account",
    "auth.reset": "Reset",
    "auth.resetSuccess": "Password reset successfully!",
    "auth.resetTitle": "Reset password",
    "auth.sending": "Sending...",
    "auth.serverError": "Something went wrong.",
    "auth.signIn": "Sign in",
    "auth.submit": "Submit",
    "auth.wait": "Please wait",
    "auth.welcomeBack": "Welcome back",
    "contact.address": "Our location",
    "contact.addressText": "Supporting local commerce throughout the country.",
    "contact.call": "Call us",
    "contact.email": "Email address",
    "contact.formIntro": "Fill in the fields below to contact us.",
    "contact.formTitle": "Send us a message",
    "contact.intro": "Have a question about ShopInMada? Our team is available to help.",
    "contact.kicker": "Get in touch",
    "contact.message": "Your message",
    "contact.messageExample": "Describe your request…",
    "contact.name": "Your name",
    "contact.nameExample": "e.g. Rakoto Jean",
    "contact.phoneText": "We would be happy to talk with you.",
    "contact.sendError": "Unable to send your message.",
    "contact.sending": "Sending…",
    "contact.subject": "Subject",
    "contact.subjectExample": "How can we help you?",
    "contact.submit": "Send message",
    "contact.title": "Let’s talk about your project.",
    "footer.about": "About",
    "footer.contact": "Contact us",
    "footer.pro": "Pro plan",
    "footer.rights": "All rights reserved.",
    "footer.tagline": "Madagascar’s local marketplace",
    "home.buyLocal": "Shop local",
    "home.byCity": "Explore offers by city and shop.",
    "home.curated": "Picked for you",
    "home.discoveryText": "Find what you need and contact shops directly.",
    "home.discoveryTitle": "It all starts with a great find.",
    "home.everywhere": "Across the country",
    "home.exploreRegions": "Explore by region",
    "home.exploreRegionsText": "Narrow your search using the cities available in the marketplace.",
    "home.featureAnalytics": "Advanced analytics",
    "home.featureListings": "Unlimited listings",
    "home.featurePromotions": "Exclusive promotions",
    "home.featureSearch": "Featured in search",
    "home.featureStorePage": "Custom shop page",
    "home.featureSupport": "Priority support",
    "home.forProfessionals": "For professionals",
    "home.growShops": "Help local shops grow",
    "home.heroAlt": "An illustration of a ShopInMada shopping bag surrounded by products",
    "home.intro": "Explore unique products and support shops across Madagascar. Your next great find is here.",
    "home.kicker": "Madagascar’s marketplace, one click away",
    "home.localFinds": "Local gems",
    "home.localShops": "Local shops",
    "home.localShopsText": "A place for small businesses and local brands.",
    "home.localShopsTitle": "Malagasy shops",
    "home.meetShops": "Meet the shops",
    "home.meetShopsText": "Browse products and information shared by each seller.",
    "home.noProducts": "Products are coming soon.",
    "home.perMonth": "/ month",
    "home.planAdvancedAnalytics": "Advanced analytics",
    "home.planCustomCategories": "Custom categories",
    "home.planLoading": "Loading plan price…",
    "home.planMaxProducts": "Up to {count} products",
    "home.planPrioritySupport": "Priority support",
    "home.planUnavailable": "Pricing is currently unavailable",
    "home.planUnlimited": "Unlimited products",
    "home.popularProducts": "New arrivals",
    "home.proDescription": "Tools to showcase your catalog and manage your business.",
    "home.proSlogan": "Put your shop in the spotlight.",
    "home.proText": "Grow your online presence and show your products to new customers on ShopInMada.",
    "home.proTitle": "Give your shop more visibility.",
    "home.productLoadError": "Unable to load products.",
    "home.productsForAll": "Products for everyone",
    "home.search": "A product, a shop, an idea...",
    "home.searchEasy": "Search with ease",
    "home.searchEasyText": "Browse the catalog or find a specific item in seconds.",
    "home.selection": "Featured today",
    "home.simpleExperience": "A simple experience",
    "home.startSelling": "Get started",
    "home.storyKicker": "A marketplace from Madagascar",
    "home.storyLink": "Explore the marketplace",
    "home.storyText": "ShopInMada brings Malagasy shops together with people looking for unique products. Discover, connect with sellers, and support local commerce.",
    "home.storyTitle": "Madagascar’s craftsmanship deserves a borderless showcase.",
    "home.supportLocal": "A purchase that gives back",
    "home.supportText": "Every discovery helps local talent shine.",
    "home.title": "Discover local finds",
    "home.titleAccent": "that make a difference.",
    "home.viewAll": "Browse all products",
    "nav.mobileAccount": "Account",
    "nav.mobileCart": "Cart",
    "nav.mobileExplore": "Explore",
    "nav.mobileHome": "Home",
    "nav.mobileNavigation": "Mobile navigation",
    "nav.mobileSell": "Sell",
    "order.accountReference": "Account reference",
    "order.beneficiary": "Recipient",
    "order.cancel": "Cancel",
    "order.cancelSuborder": "Cancel this sub-order",
    "order.carrier": "Carrier",
    "order.checkingItems": "Checking items…",
    "order.confirmReceipt": "Confirm receipt",
    "order.continueShopping": "Continue shopping",
    "order.date": "Order placed",
    "order.declarePayment": "Declare payment",
    "order.declaredReference": "Declared reference",
    "order.delivery": "Delivery",
    "order.expiration": "the deadline expires",
    "order.follow": "Track this order",
    "order.guestLinkHint": "Open the complete tracking link sent after your order was placed.",
    "order.historyTitle": "Marketplace order history",
    "order.iPaid": "I’ve paid, declare payment",
    "order.method": "Method",
    "order.noOrders": "No multi-seller orders yet.",
    "order.notFound": "Order not found.",
    "order.paySeller": "Pay the seller directly",
    "order.payment": "Payment",
    "order.payment.confirmed": "confirmed",
    "order.payment.declared": "declared",
    "order.payment.due": "due",
    "order.paymentMethod.airtel_money": "Airtel Money",
    "order.paymentMethod.mvola": "MVola",
    "order.paymentMethod.orange_money": "Orange Money",
    "order.paymentMethod.paiement_livraison": "Cash on delivery",
    "order.paymentMethod.virement": "Bank transfer",
    "order.phoneAccount": "Phone / account",
    "order.refunded": "Refunded",
    "order.repeat": "Order again",
    "order.reportDispute": "Report a dispute",
    "order.screenshotOptional": "Screenshot (optional)",
    "order.sellerAccept": "The seller must accept your request before",
    "order.sellerMustConfirm": "The seller must confirm receipt of the funds.",
    "order.shop": "Shop",
    "order.shopCountPlural": "{count} shops",
    "order.shopCountSingle": "{count} shop",
    "order.status.annulee": "Canceled",
    "order.status.en_attente_paiement": "Payment required",
    "order.status.en_attente_vendeur": "Waiting for seller response",
    "order.status.en_preparation": "Preparing",
    "order.status.expediee": "Shipped",
    "order.status.expiree": "Expired",
    "order.status.litige": "Disputed",
    "order.status.livree": "Delivered",
    "order.status.paiement_confirme": "Payment confirmed",
    "order.status.paiement_declare": "Payment declared, under review",
    "order.status.partiellement_terminee": "Partially completed",
    "order.status.refusee": "Declined",
    "order.status.terminee": "Completed",
    "order.statusHistory": "Status history",
    "order.suborder": "Sub-order",
    "order.subtotal": "Shop subtotal",
    "order.toPay": "Payable to {shop}",
    "order.tracking": "Order tracking",
    "order.trackingNumber": "Tracking",
    "order.transactionReference": "Transaction reference",
    "order.viewEvidence": "View submitted screenshot",
    "order.yourOrder": "Your order",
    "product.addToCart": "Add to cart",
    "product.notFound": "This product does not exist or is no longer published.",
    "product.outOfStock": "Out of stock",
    "product.unavailable": "Product unavailable",
    "shop.allCities": "All cities",
    "shop.allProducts": "All products",
    "shop.applyFilters": "Apply filters",
    "shop.categories": "Categories",
    "shop.categoryLoadError": "Unable to load categories right now.",
    "shop.categoryLabel": "Category",
    "shop.categoryTitle": "Products in this category",
    "shop.city": "City",
    "shop.closeCategories": "Close categories",
    "shop.collapseCategories": "Collapse categories",
    "shop.explore": "Explore",
    "shop.hideSubcategories": "Hide subcategories of",
    "shop.loadError": "Unable to load products.",
    "shop.loading": "Loading products…",
    "shop.loadingCategories": "Loading categories…",
    "shop.maximumPrice": "Maximum price (MGA)",
    "shop.minimumPrice": "Minimum price (MGA)",
    "shop.newest": "Newest",
    "shop.next": "Next",
    "shop.noMaximum": "No maximum",
    "shop.noMinimum": "No minimum",
    "shop.noResults": "No products match your search.",
    "shop.noResultsHint": "Try another search or browse all categories.",
    "shop.otherProducts": "Other products",
    "shop.of": "of",
    "shop.oldest": "Oldest",
    "shop.pageOf": "Page",
    "shop.pageProductCount": "{count} on this page",
    "shop.pagination": "Product pagination",
    "shop.previous": "Previous",
    "shop.priceAscending": "Price: low to high",
    "shop.priceDescending": "Price: high to low",
    "shop.productCount": "{count} product(s)",
    "shop.resultsFor": "Results for",
    "shop.showCategories": "Show categories",
    "shop.showSubcategories": "Show subcategories of",
    "shop.sortBy": "Sort by",
    "shop.storeTitle": "Explore this shop",
    "shop.title": "All products",
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);
export { LanguageContext };

function getInitialLanguage(): Language {
  try {
    return localStorage.getItem(storageKey) === "en" ? "en" : "fr";
  } catch {
    return "fr";
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(getInitialLanguage);
  const { user, authReady } = useAuth();

  useEffect(() => {
    if (authReady && user?.preferences?.language) {
      setLanguage(user.preferences.language);
    }
  }, [authReady, user?._id, user?.preferences?.language]);

  useEffect(() => {
    try {
      localStorage.setItem(storageKey, language);
    } catch {
      // Language selection still works for the current session.
    }
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) =>
    translationBundles[language][key] ??
    translationBundles.fr[key] ??
    catalogs[language][key] ??
    catalogs.fr[key] ??
    key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
